version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: meena
      POSTGRES_PASSWORD: meena123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: meena51/notes-app-backend:latest
    # build: ./backend
    container_name: flask_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://meena:meena123@db:5432/tasks_db

  frontend:
    image: meena51/notes-app-frontend:latest
    # build: ./frontend
    container_name: react_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
